Public Suffix With SubDomain Handling
mooltipass/android_companion pull request #24
Opened 2022-04-23 16:40 UTC by shabbir81

New option added
Logic Updated for Public Suffix
Logic Added for Public Suffix with SubDomain

2022-04-26 19:48 UTC, limpkin commented
@shabbir81 : warnings during compilation:
mooltifill\PublicSuffixManager.kt: (83, 33): 'toLowerCase(): String' is deprecated. Use lowercase() instead.
mooltifill\PublicSuffixManager.kt: (83, 72): 'toLowerCase(): String' is deprecated. Use lowercase() instead.
mooltifill\PublicSuffixManager.kt: (91, 20): Condition 'strippedTokens.last() != null' is always 'true'
mooltifill\PublicSuffixManager.kt: (156, 13): Condition 'result != null' is always 'true'

2022-04-28 15:41 UTC, mathfactory approved these changes

2022-04-28 15:44 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +        return domain
unreachable code

2022-04-28 15:44 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +        return runBlocking { suffixList!!.stripPublicSuffix(domain).await() }!!
Unnecessary non-null assertion (!!) on a non-null receiver of type String

2022-04-28 15:45 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +        suffixList!!.prefetch()
'Deferred' result is unused

2022-04-28 15:47 UTC, mathfactory requested changes
See comments

2022-04-28 15:47 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +
Missing package de.mathfactory.mooltifill;

2022-04-28 15:48 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +    var suffixList: PublicSuffixList? = null
Property 'suffixList' could be private

2022-04-28 16:23 UTC, limpkin commented
@shabbir81 could you update your PR so @mathfactory could review again?

2022-04-29 10:46 UTC, shabbir81 commented
Updated code and new PR opened

2022-04-29 11:33 UTC, mathfactory requested changes

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +    private lateinit var suffixList:PublicSuffixList
suffixList is initialized in invoke(), which is called in SettingsActivity.onCreate(). It is not guaranteed, that this function is even called! (E.g. after reboot)

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +        suffixList = PublicSuffixList(context)
the PublicSuffixManager object is a global singleton. Adding a reference to the context through PublicSuffixList(context) has issues: We have at least two different contexts in the Activity- and the Service-related part of the code. Also, storing a context over global lifetime of the application probably introduces a memory leak. Instead the context should better be passed to the get*() functions if possible (one way would be to add the context as a parameter to the SubstitutionPolicy.policies(query:String) function.

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +        val isPublicSuffix = runBlocking { suffixList.isPublicSuffix(domain).await() }
Please find a way to not use runBlocking { } as this negates the effect of async programming.

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +            val suffix = runBlocking { suffixList.getPublicSuffixPlusOne(domain).await() }
Please find a way to not use runBlocking { } as this negates the effect of async programming.

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +        val isPublicSuffix = runBlocking { suffixList.isPublicSuffix(domain).await() }
Please find a way to not use runBlocking { } as this negates the effect of async programming.

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +            val tld = runBlocking { suffixList.getPublicSuffixPlusOne(domain).await() }
Please find a way to not use runBlocking { } as this negates the effect of async programming.

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/java/de/mathfactory/mooltifill/PublicSuffixManager.kt
> +    private lateinit var suffixList:PublicSuffixList
(I expect an application crash after reboot, when accessing credentials without going to the settings first)

2022-04-29 11:33 UTC, mathfactory commented on app/src/main/res/xml/root_preferences.xml
> +            app:defaultValue="PublicSuffix"
If you change the default value here, please also change it in SettingsActivity:100, which is currently "UrlSubstitutionPolicies.RemoveWww". There are two cases which lead to using a default and they are handled differently, sorry for this ;)

2022-04-29 11:43 UTC, mathfactory commented
I hope my comments do not sound too "harsh", thank you very much for the constribution! ;) I think best way would be to adapt the SubstitutionPolicy classes to be async/suspend and to pass a context in fun policies(). I can also offer to have a look into this, just give me a hint.

2022-04-29 13:18 UTC, shabbir81 commented on app/src/main/res/xml/root_preferences.xml
> +            app:defaultValue="PublicSuffix"
sure

2022-04-29 17:00 UTC, shabbir81 commented on app/src/main/res/xml/root_preferences.xml
> +            app:defaultValue="PublicSuffix"
Updated

2022-04-30 17:04 UTC, merged